version: '3.9'
services:
    db:
        container_name: db
        image: mysql:8.0.22
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: application
            MYSQL_USER: application
            MYSQL_PASSWORD: application

    phpfpm:
        container_name: php-fpm
        build:
            context: ./docker/php-fpm
            args:
                ENABLE_PHP_XDEBUG: 1
        ports:
            - "9000:9001"
        volumes:
            - ./app:/var/www/application:cached
        depends_on:
            - db

    nginx:
        container_name: nginx
        build: ./docker/nginx
        ports:
            - "80:80"
        depends_on:
            - phpfpm
        volumes:
            - ./docker/logs/nginx:/var/log/nginx:cached
            - ./app:/var/www/application:cached

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        environment:
            discovery.type: "single-node"
        ports:
            - "9200:9200"
            - "9300:9300"

    logstash:
        container_name: logstash
        image: docker.elastic.co/logstash/logstash:7.12.0
        depends_on:
            - elasticsearch
        volumes:
            - ./docker/elk/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:cached
            - ./docker/elk/logstash/conf.d:/etc/logstash/conf.d:cached
            - ./docker/logs/nginx:/var/log/nginx:cached

    kibana:
        container_name: kibana
        depends_on:
            - elasticsearch
        image: docker.elastic.co/kibana/kibana:7.12.0
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        ports:
            - "81:5601"

# Dev tools
    adminer:
        image: adminer
        environment:
            APP_ENV: dev
            ADMINER_DESIGN: pepa-linha
            ADMINER_DEFAULT_SERVER: db
        ports:
            - 8888:8080
    mail:
        image: mailhog/mailhog
        ports:
            - 1080:8025
