version: '3.9'
services:
    db:
        container_name: db
        image: mysql:8.0.22
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: application
            MYSQL_USER: application
            MYSQL_PASSWORD: application

    phpfpm:
        container_name: php-fpm
        build:
            context: ./docker/php-fpm
            args:
                ENABLE_PHP_XDEBUG: 1
        ports:
            - "9000:9001"
        volumes:
            - ./app:/var/www/application:cached
        depends_on:
            - db

    nginx:
        container_name: nginx
        build: ./docker/nginx
        ports:
            - "80:80"
        depends_on:
            - phpfpm
        volumes:
            - ./docker/logs/nginx:/var/log/nginx:cached
            - ./app:/var/www/application:cached

# Dev tools
    adminer:
        image: adminer
        environment:
            APP_ENV: dev
            ADMINER_DESIGN: pepa-linha
            ADMINER_DEFAULT_SERVER: db
        ports:
            - 8888:8080
